# Generated by Django 4.2.3 on 2023-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_candidate_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('employer', 'Employer'), ('superadmin', 'Super Admin')], default='candidate', max_length=20),
        ),
    ]
