# Generated by Django 4.2.3 on 2023-09-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
