# Generated by Django 4.2.3 on 2023-09-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_address_additionalprofileinfo_barangay_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalProfileInfo',
        ),
    ]
