# Generated by Django 4.2.3 on 2023-09-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_candidateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
    ]
