# Generated by Django 4.2.3 on 2023-09-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education_description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education_title',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institute_name',
        ),
        migrations.AddField(
            model_name='education',
            name='additional_info',
            field=models.TextField(null=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='education',
            name='educational_degree',
            field=models.CharField(max_length=255, null=True, verbose_name='Educational Degree'),
        ),
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=255, null=True, verbose_name='School Name'),
        ),
    ]
