# Generated by Django 4.2.3 on 2023-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_education_education_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='award_title',
        ),
        migrations.AddField(
            model_name='award',
            name='role',
            field=models.CharField(max_length=255, null=True, verbose_name='Role'),
        ),
    ]
