# Generated by Django 4.2.3 on 2023-09-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_award_award_title_award_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_title',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=255, null=True, verbose_name='Skill'),
        ),
    ]
