# Generated by Django 4.2.3 on 2023-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_skill_skill_title_skill_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_mastery',
        ),
        migrations.AddField(
            model_name='skill',
            name='mastery_level',
            field=models.CharField(max_length=255, null=True, verbose_name='Skill Mastery'),
        ),
    ]
