# Generated by Django 4.2.3 on 2023-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='employerprofile',
            table='custom_employer_profile',
        ),
    ]
