# Generated by Django 4.2.3 on 2023-09-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_employerprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employerprofile',
            table=None,
        ),
    ]
