# Generated by Django 4.2.3 on 2023-09-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
