# Generated by Django 4.2.3 on 2023-09-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('specializations', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('job_setup', models.CharField(max_length=255)),
                ('job_level', models.CharField(max_length=255)),
                ('experience_level', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('offered_salary', models.CharField(max_length=255)),
                ('deadline_date', models.DateField()),
                ('attachment', models.FileField(upload_to='job_attachments/')),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app.userprofile')),
            ],
        ),
    ]
