# Generated by Django 4.2.3 on 2023-09-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='street_address',
            new_name='street',
        ),
    ]
