# Generated by Django 4.2.3 on 2023-09-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_street_address_job_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
