# Generated by Django 4.2.3 on 2023-09-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_kenoh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='mastery_level',
        ),
        migrations.AddField(
            model_name='skill',
            name='expi_years',
            field=models.CharField(max_length=255, null=True, verbose_name='Years of Experience'),
        ),
    ]
