# Generated by Django 4.2.3 on 2023-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_certification_delete_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
