# Generated by Django 4.2.3 on 2023-09-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_workexperience_work_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='End Month'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Year'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Start Month'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Year'),
        ),
    ]
