# Generated by Django 4.2.3 on 2023-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_certification_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
