# Generated by Django 4.2.3 on 2023-10-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_candidateprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='year',
            new_name='certification_year',
        ),
    ]
