# Generated by Django 4.2.3 on 2023-10-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_year_certification_certification_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certification_year',
        ),
        migrations.AddField(
            model_name='certification',
            name='issue_month',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Issue Month'),
        ),
        migrations.AddField(
            model_name='certification',
            name='issue_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Issue Year'),
        ),
    ]
