# Generated by Django 4.2.3 on 2023-10-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_jobapplication_delete_kenoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
