# Generated by Django 4.2.3 on 2023-11-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_candidateprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
