# Generated by Django 4.2.3 on 2023-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_jobapplication_retention_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='certification_needed',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
