# Generated by Django 4.2.3 on 2023-11-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_jobapplication_retention_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='reason_for_turnover',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='risk_factors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
