# Generated by Django 4.2.3 on 2023-11-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_education_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='educational_degree',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
