# Generated by Django 4.2.3 on 2023-11-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_job_educational_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='retention_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='outcome',
            field=models.CharField(blank=True, choices=[('High Retention', 'High Retention'), ('Moderate Retention', 'Moderate Retention'), ('Low Retention', 'Low Retention')], max_length=255, null=True),
        ),
    ]
