# Generated by Django 4.2.3 on 2023-11-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_jobapplication_retention_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='turnover_risk_flag',
        ),
    ]
