# Generated by Django 4.2.3 on 2023-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_remove_jobapplication_turnover_risk_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='reasons_for_turnover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
