# Generated by Django 4.2.3 on 2023-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_jobapplication_reasons_for_turnover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonForTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='reasons_for_turnover',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reasons_for_turnover',
            field=models.ManyToManyField(blank=True, to='app.reasonforturnover'),
        ),
    ]
