# Generated by Django 4.2.3 on 2023-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_reasonforturnover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='reasons_for_turnover',
            field=models.ManyToManyField(to='app.reasonforturnover'),
        ),
    ]
