# Generated by Django 4.2.3 on 2023-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_jobapplication_reasons_for_turnover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='reasons_for_turnover',
        ),
        migrations.DeleteModel(
            name='ReasonForTurnover',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reasons_for_turnover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
