# Generated by Django 4.2.3 on 2023-11-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_jobapplication_reasons_for_turnover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='offered_salary',
            field=models.IntegerField(),
        ),
    ]
