# Generated by Django 4.2.3 on 2023-11-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_job_offered_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=255, verbose_name='Training Title')),
                ('training_organization', models.CharField(max_length=255, verbose_name='Training Organization')),
                ('training_description', models.TextField(verbose_name='Training Description')),
                ('location_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Type')),
                ('training_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Training Type')),
                ('start_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start Month')),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='Start Year')),
                ('end_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='End Month')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='End Year')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
